services:
  - type: web
    name: suad-busi-tech-api
    env: node
    runtime: node_20
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    autoDeploy: true
